// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/list": {
            "post": {
                "description": "Create a List with auto-set Order (set as last Order in database)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "List"
                ],
                "summary": "Create a List",
                "parameters": [
                    {
                        "description": "Title of this List",
                        "name": "list",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerInputCreateList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerList"
                        }
                    }
                }
            }
        },
        "/list/{id}": {
            "get": {
                "description": "Get a list by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "List"
                ],
                "summary": "Get List By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of list to get",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerList"
                        }
                    }
                }
            },
            "put": {
                "description": "Update list with id. Fields [Title, Order] can be updated. Changing the order will affect other lists too, just like inserting in c++ vector.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "List"
                ],
                "summary": "Update list by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of list to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Details to update",
                        "name": "list",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerInputUpdateList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerList"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete list with id. The orders of other lists will be updated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "List"
                ],
                "summary": "Delete list by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of list to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerList"
                        }
                    }
                }
            }
        },
        "/lists": {
            "get": {
                "description": "Get All Lists in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "List"
                ],
                "summary": "Get All Lists in database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerLists"
                        }
                    }
                }
            }
        },
        "/task": {
            "post": {
                "description": "Create a Task with auto-set Order (set as last Order in database) in a list specified by listID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Create a Task",
                "parameters": [
                    {
                        "description": "Details of this Task",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerInputCreateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerTask"
                        }
                    }
                }
            }
        },
        "/task/{id}": {
            "get": {
                "description": "Get a task by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get Task By ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of task to get",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerTask"
                        }
                    }
                }
            },
            "put": {
                "description": "Update task with id. Fields [Title, Order, ListID] can be updated. Changing the order will affect other tasks too, just like inserting in c++ vector. Changing list without specifying Order will put it in the last order.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Update task by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of task to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Details to update",
                        "name": "task",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerInputUpdateTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerTask"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete task with id. The orders of other tasks will be updated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Delete task by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of task to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerTask"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "description": "Get All Tasks in database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Get All Tasks in database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerTasks"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.List": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Task"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerInputCreateList": {
            "type": "object",
            "properties": {
                "Order": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerInputCreateTask": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "ListID": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerInputUpdateList": {
            "type": "object",
            "properties": {
                "Order": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerInputUpdateTask": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "ListID": {
                    "type": "integer"
                },
                "Order": {
                    "type": "integer"
                },
                "Title": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerList": {
            "type": "object",
            "properties": {
                "list": {
                    "$ref": "#/definitions/models.List"
                }
            }
        },
        "models.SwaggerLists": {
            "type": "object",
            "properties": {
                "lists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.List"
                    }
                }
            }
        },
        "models.SwaggerTask": {
            "type": "object",
            "properties": {
                "task": {
                    "$ref": "#/definitions/models.Task"
                }
            }
        },
        "models.SwaggerTasks": {
            "type": "object",
            "properties": {
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Task"
                    }
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "dueDate": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "listID": {
                    "type": "integer"
                },
                "order": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
