definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.List:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      order:
        type: integer
      tasks:
        items:
          $ref: '#/definitions/models.Task'
        type: array
      title:
        type: string
      updatedAt:
        type: string
    type: object
  models.SwaggerList:
    properties:
      list:
        $ref: '#/definitions/models.List'
    type: object
  models.SwaggerLists:
    properties:
      list:
        items:
          $ref: '#/definitions/models.List'
        type: array
    type: object
  models.Task:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      dueDate:
        type: string
      id:
        type: integer
      listID:
        type: integer
      order:
        type: integer
      title:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /list:
    post:
      consumes:
      - application/json
      description: Create a List with auto-set Order (set as last Order in database)
      parameters:
      - description: Title of this List
        in: body
        name: list
        required: true
        schema:
          $ref: '#/definitions/models.List'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SwaggerList'
      summary: Create a List
      tags:
      - List
  /lists:
    get:
      consumes:
      - application/json
      description: Get All Lists in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SwaggerLists'
      summary: Get All Lists in database
      tags:
      - List
swagger: "2.0"
